###############################################################################
# CS/CNS 171 Fall 2016
#
###############################################################################
CC = g++
FLAGS = -g
#SOURCES = *.h *.cpp
SOURCES = *.cpp

EXENAME = parsing

all: $(SOURCES)
	$(CC) $(FLAGS) -o $(EXENAME) $(SOURCES)

clean:
	rm -f *.o $(EXENAME)

.PHONY: all clean

